Proyecto Final 4/Proyecto Final 4/Models/Permisos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int Id { get; set; }
        public short CodigoE { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}

Proyecto Final 4/Proyecto Final 4/Controllers/CargosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final_4.Models;

namespace Proyecto_Final_4.Controllers
{
    public class CargosController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Cargos
        public ActionResult Index()
        {
            return View(db.CargosSet.ToList());
        }

        // GET: Cargos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cargos cargos = db.CargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // GET: Cargos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cargos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cargo")] Cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.CargosSet.Add(cargos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cargos);
        }

        // GET: Cargos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cargos cargos = db.CargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: Cargos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Cargo")] Cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cargos);
        }

        // GET: Cargos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cargos cargos = db.CargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: Cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cargos cargos = db.CargosSet.Find(id);
            db.CargosSet.Remove(cargos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto Final 4/Proyecto Final 4/Controllers/NominasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final_4.Models;

namespace Proyecto_Final_4.Controllers
{
    public class NominasController : Controller
    {
        private Model1Container db = new Model1Container();

        public ActionResult Totalizar()
        {
            ViewBag.TotalSalario = db.EmpleadosSet.Sum(a => a.Salario);
            ViewBag.TotalEmpleados = db.EmpleadosSet.Count();

        //    var query = (from a in db.EmpleadosSet
          //               select a);

            db.SaveChanges();
            return View();
        }


        // GET: Nominas
        public ActionResult Index()
        {
            return View(db.NominasSet.ToList());
        }

        // GET: Nominas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nominas nominas = db.NominasSet.Find(id);
            if (nominas == null)
            {
                return HttpNotFound();
            }
            return View(nominas);
        }

        // GET: Nominas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Nominas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Anio,Mes,Monto")] Nominas nominas)
        {
            if (ModelState.IsValid)
            {
                db.NominasSet.Add(nominas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nominas);
        }

        // GET: Nominas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nominas nominas = db.NominasSet.Find(id);
            if (nominas == null)
            {
                return HttpNotFound();
            }
            return View(nominas);
        }

        // POST: Nominas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Anio,Mes,Monto")] Nominas nominas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nominas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nominas);
        }

        // GET: Nominas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nominas nominas = db.NominasSet.Find(id);
            if (nominas == null)
            {
                return HttpNotFound();
            }
            return View(nominas);
        }

        // POST: Nominas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nominas nominas = db.NominasSet.Find(id);
            db.NominasSet.Remove(nominas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto Final 4/Proyecto Final 4/Controllers/PermisosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final_4.Models;

namespace Proyecto_Final_4.Controllers
{
    public class PermisosController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Permisos
        public ActionResult Index()
        {
            return View(db.PermisosSet.ToList());
        }

        // GET: Permisos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permisos permisos = db.PermisosSet.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            return View(permisos);
        }

        // GET: Permisos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Permisos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CodigoE,Desde,Hasta,Comentarios")] Permisos permisos)
        {
            if (ModelState.IsValid)
            {
                db.PermisosSet.Add(permisos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permisos);
        }

        // GET: Permisos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permisos permisos = db.PermisosSet.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            return View(permisos);
        }

        // POST: Permisos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CodigoE,Desde,Hasta,Comentarios")] Permisos permisos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permisos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permisos);
        }

        // GET: Permisos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permisos permisos = db.PermisosSet.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            return View(permisos);
        }

        // POST: Permisos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Permisos permisos = db.PermisosSet.Find(id);
            db.PermisosSet.Remove(permisos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto Final 4/Proyecto Final 4/Controllers/SalidasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Final_4.Models;

namespace Proyecto_Final_4.Controllers
{
    public class SalidasController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Salidas
        public ActionResult Index()
        {
            return View(db.SalidasSet.ToList());
        }

        // GET: Salidas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salidas salidas = db.SalidasSet.Find(id);
            if (salidas == null)
            {
                return HttpNotFound();
            }
            return View(salidas);
        }

        // GET: Salidas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Salidas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CodigoE,TipoSalida,Motivo,FechaSalida")] Salidas salidas)
        {
            if (ModelState.IsValid)
            {
                db.SalidasSet.Add(salidas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(salidas);
        }

        // GET: Salidas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salidas salidas = db.SalidasSet.Find(id);
            if (salidas == null)
            {
                return HttpNotFound();
            }
            return View(salidas);
        }

        // POST: Salidas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CodigoE,TipoSalida,Motivo,FechaSalida")] Salidas salidas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salidas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(salidas);
        }

        // GET: Salidas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salidas salidas = db.SalidasSet.Find(id);
            if (salidas == null)
            {
                return HttpNotFound();
            }
            return View(salidas);
        }

        // POST: Salidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Salidas salidas = db.SalidasSet.Find(id);
            db.SalidasSet.Remove(salidas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto Final 4/Proyecto Final 4/Views/Permisos/Create.cshtml
@model Proyecto_Final_4.Models.Permisos

@{
    ViewBag.Title = "Create";
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>


    <!-- Required Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Page Title -->
    <title>About</title>
    @Styles.Render("~/Content/css")

    <style>
        .heading {
            color: #FFFFFF;
        }
    </style>

</head>
<body>

    <!-- Preloader Starts -->
    <div class="preloader">
        <div class="spinner"></div>
    </div>
    <!-- Preloader End -->
    <!-- Header Area Starts -->
    <header class="header-area single-page">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-10">
                        <div class="custom-navbar">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                        <div class="main-menu main-menu-light">

                            <ul>
                                <li>@Html.ActionLink("Inicio", "Inicio", "Home")</li>
                                <li>
                                    <a href="#">Crear</a>
                                    <ul class="sub-menu">
                                        <li>@Html.ActionLink("Empleado", "Create", "Empleados")</li>
                                        <li>@Html.ActionLink("Departamento", "Create", "Departamentos")</li>
                                        <li>@Html.ActionLink("Cargo", "Create", "Cargos")</li>
                                        <li>@Html.ActionLink("Nomina", "Create", "Nominas")</li>
                                        <li>@Html.ActionLink("Salida", "Create", "Salidas")</li>
                                        <li>@Html.ActionLink("Permiso", "Create", "Permisos")</li>
                                        <li>@Html.ActionLink("Licencia", "Create", "Licencias")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Informes</a>
                                    <ul class="sub-menu">
                                        <li>@Html.ActionLink("Empleado", "Index", "Empleados")</li>
                                        <li>@Html.ActionLink("Departamento", "Index", "Departamentos")</li>
                                        <li>@Html.ActionLink("Cargo", "Index", "Cargos")</li>
                                        <li>@Html.ActionLink("Nominas", "Index", "Nominas")</li>
                                        <li>@Html.ActionLink("NominaTotal", "Totalizar", "Nominas")</li>
                                        <li>@Html.ActionLink("Salida", "Index", "Salidas")</li>
                                        <li>@Html.ActionLink("Permiso", "Index", "Permisos")</li>
                                        <li>@Html.ActionLink("Licencia", "Index", "Licencias")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-title text-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <h2>Crear</h2>

                        <form>

                            @Html.AntiForgeryToken()


                            <div class="form-horizontal">
                                <h2>Permiso</h2>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <p>  @Html.LabelFor(model => model.CodigoE, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CodigoE, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CodigoE, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <p>      @Html.LabelFor(model => model.Desde, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Desde, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Desde, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <p>    @Html.LabelFor(model => model.Hasta, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Hasta, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Hasta, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <p>       @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Comentarios, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="template-btn" />
                                    </div>
                                </div>
                            </div>
                            
                        </form>

                        <div class="secondary-btn">
                            <span class="flaticon-next">
                                @Html.ActionLink("Volver", "Inicio", "Home")
                            </span>

                        </div>



                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->
    <!-- Feature Area Starts -->
    </div>
    </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-6">
                    <span>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | Trabajo hecho por 20174985 y 20174979 <i class="fa fa-heart-o" aria-hidden="true"></i>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </span>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="social-icons">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </footer>
    <!-- Footer Area End -->
    <!-- Javascript -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

</body>
</html>

Proyecto Final 4/Proyecto Final 4/Views/Permisos/Delete.cshtml
@model Proyecto_Final_4.Models.Permisos

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h2>Permisos</h2>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <p>  @Html.DisplayNameFor(model => model.CodigoE)</p>
            </dt>
    
            <dd>
                <p>   @Html.DisplayFor(model => model.CodigoE)</p>
            </dd>
    
            <dt>
                <p>   @Html.DisplayNameFor(model => model.Desde)</p>
            </dt>
    
            <dd>
                <p>   @Html.DisplayFor(model => model.Desde)</p>
            </dd>
    
            <dt>
                <p>  @Html.DisplayNameFor(model => model.Hasta)</p>
            </dt>
    
            <dd>
                <p>    @Html.DisplayFor(model => model.Hasta)</p>
            </dd>
    
            <dt>
                <p>     @Html.DisplayNameFor(model => model.Comentarios)</p>
            </dt>
    
            <dd>
                <p>  @Html.DisplayFor(model => model.Comentarios)</p>
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="template-btn" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Proyecto Final 4/Proyecto Final 4/Views/Permisos/Details.cshtml
@model Proyecto_Final_4.Models.Permisos

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Permisos</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <p>    @Html.DisplayNameFor(model => model.CodigoE)</p>
            </dt>
    
            <dd>
                <p> @Html.DisplayFor(model => model.CodigoE)</p>
            </dd>
    
            <dt>
                <p>  @Html.DisplayNameFor(model => model.Desde)</p>
            </dt>
    
            <dd>
                <p>   @Html.DisplayFor(model => model.Desde)</p>
            </dd>
    
            <dt>
                <p> @Html.DisplayNameFor(model => model.Hasta)</p>
            </dt>
    
            <dd>
                <p>  @Html.DisplayFor(model => model.Hasta)</p>
            </dd>
    
            <dt>
                <p>  @Html.DisplayNameFor(model => model.Comentarios)</p>
            </dt>
    
            <dd>
                <p>  @Html.DisplayFor(model => model.Comentarios) </p>
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Proyecto Final 4/Proyecto Final 4/Views/Permisos/Edit.cshtml
@model Proyecto_Final_4.Models.Permisos

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Permisos</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
             <p>   @Html.LabelFor(model => model.CodigoE, htmlAttributes: new { @class = "control-label col-md-2" })  </p>   
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CodigoE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodigoE, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <p>  @Html.LabelFor(model => model.Desde, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Desde, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Desde, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <p>   @Html.LabelFor(model => model.Hasta, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hasta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hasta, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <p>   @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Comentarios, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Editar" class="template-btn" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>